// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ck/cluster": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取ClickHouse集群",
                "summary": "获取ClickHouse集群",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{\"test\":{\"hosts\":[\"192.168.101.105\"],\"port\":9000,\"user\":\"eoi\",\"password\":\"123456\",\"database\":\"default\",\"cluster\":\"test\",\"zkNodes\":[\"192.168.101.102\"],\"zkPort\":2181,\"isReplica\":false}}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "更新ClickHouse集群",
                "summary": "更新ClickHouse集群",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CkImportConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "导入ClickHouse集群",
                "summary": "导入ClickHouse集群",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CkImportConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ck/cluster/{clusterName}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除ClickHouse集群",
                "summary": "删除ClickHouse集群",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ck/destroy/{clusterName}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "销毁ClickHouse集群",
                "summary": "销毁ClickHouse集群",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ck/get/{clusterName}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取ClickHouse集群信息",
                "summary": "获取ClickHouse集群信息",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":{\"status\":\"green\",\"version\":\"20.8.5.45\",\"nodes\":[{\"ip\":\"192.168.101.105\",\"hostname\":\"vm101105\",\"status\":\"green\"}]}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ck/node/{clusterName}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "添加ClickHouse集群节点",
                "summary": "添加ClickHouse集群节点",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddNodeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除ClickHouse集群节点",
                "summary": "删除ClickHouse集群节点",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "192.168.101.105",
                        "description": "node ip address",
                        "name": "ip",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ck/query/{clusterName}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "执行query命令",
                "summary": "执行query命令",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "show databases",
                        "description": "sql",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[[\"name\"],[\"default\"],[\"system\"]]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ck/rebalance/{clusterName}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "均衡ClickHouse集群",
                "summary": "均衡ClickHouse集群",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ck/start/{clusterName}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "启动ClickHouse集群",
                "summary": "启动ClickHouse集群",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ck/stop/{clusterName}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "停止ClickHouse集群",
                "summary": "停止ClickHouse集群",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ck/table/{clusterName}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "描述表",
                "summary": "描述表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "default",
                        "description": "database name",
                        "name": "database",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "test_table",
                        "description": "table name",
                        "name": "tableName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[{\"name\":\"_timestamp\",\"type\":\"DateTime\",\"defaultType\":\"\",\"defaultExpression\":\"\",\"comment\":\"\",\"codecExpression\":\"\",\"ttlExpression\":\"\"}]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改表",
                "summary": "修改表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AlterCkTableReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建表",
                "summary": "创建表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateCkTableReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除表",
                "summary": "删除表",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "default",
                        "description": "database name",
                        "name": "database",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "test_table",
                        "description": "table name",
                        "name": "tableName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/ck/upgrade/{clusterName}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "升级ClickHouse集群",
                "summary": "升级ClickHouse集群",
                "parameters": [
                    {
                        "type": "string",
                        "default": "test",
                        "description": "cluster name",
                        "name": "clusterName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "20.8.5.45",
                        "description": "package version",
                        "name": "packageVersion",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/deploy/ck": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "部署clickhouse",
                "summary": "部署clickhouse",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DeployCkReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":nil}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/metric/query": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询指标",
                "summary": "查询指标",
                "parameters": [
                    {
                        "type": "string",
                        "default": "ClickHouseMetrics_Read",
                        "description": "metric name",
                        "name": "metric",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1606290000",
                        "description": "metric time",
                        "name": "time",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[{\"metric\":{\"__name__\":\"ClickHouseMetrics_Read\",\"instance\":\"192.168.101.105:9363\",\"job\":\"clickhouse_exporter\"},\"value\":[1606290000,\"2\"]}]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/metric/query_range": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询指标范围",
                "summary": "查询指标范围",
                "parameters": [
                    {
                        "type": "string",
                        "default": "ClickHouseMetrics_Read",
                        "description": "metric name",
                        "name": "metric",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1606290000",
                        "description": "start time",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1606290120",
                        "description": "end time",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "60",
                        "description": "step window",
                        "name": "step",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[{\"metric\":{\"__name__\":\"ClickHouseMetrics_Read\",\"instance\":\"192.168.101.105:9363\",\"job\":\"clickhouse_exporter\"},\"values\":[[1606290000,\"2\"],[1606290060,\"2\"],[1606290120,\"2\"]]}]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/package": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取安装包列表",
                "summary": "获取安装包列表",
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":[\"20.8.5.45\"]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传安装包",
                "consumes": [
                    "multipart/form-data"
                ],
                "summary": "上传安装包",
                "parameters": [
                    {
                        "type": "file",
                        "description": "安装包",
                        "name": "package",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除包",
                "summary": "删除包",
                "parameters": [
                    {
                        "type": "string",
                        "default": "20.8.5.45",
                        "description": "package version",
                        "name": "packageVersion",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"success\",\"data\":null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "登陆",
                "summary": "登陆",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"msg\":\"ok\",\"data\":{\"username\":\"ckman\",\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\"}}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AddNodeReq": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "example": "192.168.101.108"
                },
                "shard": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "model.AlterCkTableReq": {
            "type": "object",
            "properties": {
                "add": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CkTableNameTypeAfter"
                    }
                },
                "database": {
                    "type": "string",
                    "example": "default"
                },
                "drop": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "age"
                    ]
                },
                "modify": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CkTableNameType"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "test_table"
                }
            }
        },
        "model.CkDeployConfig": {
            "type": "object",
            "properties": {
                "ckTcpPort": {
                    "type": "integer",
                    "example": 9000
                },
                "clusterName": {
                    "type": "string",
                    "example": "test"
                },
                "packageVersion": {
                    "type": "string",
                    "example": "20.8.5.45"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "path": {
                    "type": "string",
                    "example": "/data01/"
                },
                "shards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CkShard"
                    }
                },
                "user": {
                    "type": "string",
                    "example": "ck"
                },
                "zkNodes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "192.168.101.102",
                        "192.168.101.105",
                        "192.168.101.107"
                    ]
                },
                "zkPort": {
                    "type": "integer",
                    "example": 2181
                }
            }
        },
        "model.CkImportConfig": {
            "type": "object",
            "properties": {
                "cluster": {
                    "type": "string",
                    "example": "test"
                },
                "hosts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "192.168.101.105",
                        "192.168.101.107"
                    ]
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "port": {
                    "type": "integer",
                    "example": 9000
                },
                "user": {
                    "type": "string",
                    "example": "ck"
                },
                "zkNodes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "192.168.101.102",
                        "192.168.101.105",
                        "192.168.101.107"
                    ]
                },
                "zkPort": {
                    "type": "integer",
                    "example": 2181
                }
            }
        },
        "model.CkReplica": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "example": "192.168.101.105"
                }
            }
        },
        "model.CkShard": {
            "type": "object",
            "properties": {
                "replicas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CkReplica"
                    }
                }
            }
        },
        "model.CkTableNameType": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "_timestamp"
                },
                "type": {
                    "type": "string",
                    "example": "DateTime"
                }
            }
        },
        "model.CkTableNameTypeAfter": {
            "type": "object",
            "properties": {
                "after": {
                    "type": "string",
                    "example": "_timestamp"
                },
                "name": {
                    "type": "string",
                    "example": "age"
                },
                "type": {
                    "type": "string",
                    "example": "Int32"
                }
            }
        },
        "model.CkTablePartition": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "_timestamp"
                },
                "policy": {
                    "description": "0 split partition by day\n1 split partition by week\n2 split partition by month",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "model.CreateCkTableReq": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": "default"
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CkTableNameType"
                    }
                },
                "name": {
                    "type": "string",
                    "example": "test_table"
                },
                "order": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "_timestamp"
                    ]
                },
                "partition": {
                    "$ref": "#/definitions/model.CkTablePartition"
                }
            }
        },
        "model.DeployCkReq": {
            "type": "object",
            "properties": {
                "clickhouse": {
                    "$ref": "#/definitions/model.CkDeployConfig"
                },
                "hosts": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "192.168.101.105"
                    ]
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "user": {
                    "type": "string",
                    "example": "root"
                }
            }
        },
        "model.LoginReq": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "63cb91a2ceb9d4f7c8b1ba5e50046f52"
                },
                "username": {
                    "type": "string",
                    "example": "ckman"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger Example API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
